# CREATION OF ARRAY USING NUMPY

In [2]:
#EXP.NO.: 5

In [4]:
#Aim : Creating Array using Numpy

In [6]:
#Name: UBAIDUR RAHMAN
#Roll No.: 57
#Sec: B
#Subject:ET - 1


In [8]:
import numpy as np

In [10]:
array_1d = np.array([1, 2, 3, 4, 5])
print(array_1d)


[1 2 3 4 5]


In [12]:
array_2d = np.array([[1, 2, 3], [4, 5, 6]])
print(array_2d)

[[1 2 3]
 [4 5 6]]


In [14]:
zeros_array = np.zeros((3, 3))
print(zeros_array)


[[0. 0. 0.]
 [0. 0. 0.]
 [0. 0. 0.]]


In [16]:
ones_array = np.ones((2, 4))
print(ones_array)

[[1. 1. 1. 1.]
 [1. 1. 1. 1.]]


In [18]:
range_array = np.arange(0, 10, 2) # Start, stop, step
print(range_array)

[0 2 4 6 8]


In [20]:
random_array = np.random.rand(3, 3)
print(random_array)

[[0.50916126 0.41514259 0.11571979]
 [0.94391903 0.42912861 0.83837548]
 [0.68384982 0.27671044 0.92058811]]
